---
title: "Gastos dos Deputados"
author: "Gustavo Monteiro"
date: "27 de agosto de 2018"
output: html_document
---

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(gridExtra)

data = read_csv("./data.csv")
limit = read.csv("./limit.csv")
options(scipen = 999)
```

```{r warning=FALSE}
# Join two datasets by UF column to use state ceap spending limit.
colnames(data)[3] <- "UF"
data = data %>%
  full_join(limit, by=c("UF", "UF"))
```


```{r}
# Quais são os deputados que gastaram mais dinheiro da CEAP? Quais são os mais econômicos?
summarized_data = data %>% 
    filter(valorDocumento > 0) %>% 
    group_by(nomeParlamentar) %>% 
    summarise(gastos = sum(valorDocumento))

more_spenders <- summarized_data %>% 
  top_n(5, gastos) %>% 
  ggplot(aes(x = reorder(nomeParlamentar, gastos), y = gastos)) +
  guides(fill = guide_legend('Deputados')) +
  labs(x='Deputados', y='Gasto total') + 
  geom_col(width = 0.5) +
  coord_flip()

less_expenders <- summarized_data %>%
  arrange(gastos) %>%
  slice(1:5) %>%
  ggplot(aes(x = reorder(nomeParlamentar, gastos), y = gastos)) +
  guides(fill = guide_legend('Deputados')) +
  labs(x='Deputados', y='Gasto total') + 
  geom_col(width = 0.5) +
  coord_flip()

grid.arrange(more_spenders, less_expenders, nrow = 2)
```

```{r}
# Quais os estados cujos deputados gastam mais no exterior? Quais os estados cujos deputados gastam menos no exterior?
e_exprenses = data %>% 
  filter(tipoDocumento == 2) %>% 
  group_by(nomeParlamentar) %>% 
  summarise(gastos = sum(valorDocumento))

greatest_backpackers <- e_exprenses %>% 
  top_n(5, gastos) %>% 
  ggplot(aes(x = reorder(nomeParlamentar, gastos), y = gastos, fill = nomeParlamentar)) +
  guides(fill = guide_legend('Deputados')) +
  labs(x='Deputados', y='Gasto total') + 
  geom_col(width = 0.7) +
  coord_flip()

less_backpackers <- e_exprenses %>% 
  arrange(gastos) %>%
  slice(1:5) %>%
  ggplot(aes(x = reorder(nomeParlamentar, gastos), y = gastos, fill = nomeParlamentar)) +
  guides(fill = guide_legend('Deputados')) +
  labs(x='Deputados', y='Gasto total') + 
  geom_col(width = 0.7) +
  coord_flip()

grid.arrange(greatest_backpackers, less_backpackers, nrow = 2)
```

```{r}
# Quais os partidos cujos parlamentares mais usam CEAP no estado da Paraíba? Quais são os que menos usam? Mesmas perguntas considerando valores em R$.
part = data %>%
  filter(UF == "PB") %>% 
  group_by(sgPartido) %>% 
  summarise(gastos = sum(valorDocumento), n = n())

top_spenders_R <- part %>% 
  top_n(5, gastos) %>% 
  ggplot(aes(x = reorder(sgPartido, gastos), y = gastos, fill = sgPartido)) +
  guides(fill = guide_legend('Partidos')) +
  labs(x='Partidos', y='Gasto total') + 
  geom_col(width = 0.7) +
  coord_flip()

less_spenders_R <- part %>% 
  arrange(gastos) %>%
  slice(1:5) %>%
  ggplot(aes(x = reorder(sgPartido, gastos), y = gastos, fill = sgPartido)) +
  guides(fill = guide_legend('Partidos')) +
  labs(x='Partidos', y='Gasto total') + 
  geom_col(width = 0.7) +
  coord_flip()

grid.arrange(top_spenders_R, less_spenders_R, nrow = 2)
```
```{r}
top_spenders_N <- part %>% 
  top_n(5, n) %>% 
  ggplot(aes(x = reorder(sgPartido, n), y = gastos, fill = sgPartido)) +
  guides(fill = guide_legend('Partidos')) +
  labs(x='Partidos', y='Vezes que usou o CEAP') + 
  geom_col(width = 0.7) +
  coord_flip()

less_spenders_N <- part %>% 
  arrange(n) %>%
  slice(1:5) %>%
  ggplot(aes(x = reorder(sgPartido, n), y = gastos, fill = sgPartido)) +
  guides(fill = guide_legend('Partidos')) +
  labs(x='Partidos', y='Vezes que usou o CEAP') + 
  geom_col(width = 0.7) +
  coord_flip()

grid.arrange(top_spenders_N, less_spenders_N, nrow = 2)
```



```{r}
# Quais os deputados que mais ultrapassam o limite de CEAP do seu estado?
rm_limit = data %>% 
  filter(!is.na(dataEmissao)) %>% 
  group_by(nomeParlamentar, format(dataEmissao, "%m"), format(dataEmissao, "%y")) %>% 
  summarise(gastos = sum(valorLíquido), limite = mean(limite_mensal)) %>% 
  filter(gastos > limite) %>%
  group_by(nomeParlamentar) %>%
  summarise(gastos = max(gastos)) %>% 
  top_n(10, gastos)
```

```{r}
# Quais estados cujos parlamentares gastam mais com passagens aéreas?
flyers = data %>%
  filter(tipoDespesa == "Emissão Bilhete Aéreo") %>% 
  group_by(UF) %>% 
  summarise(gastos = sum(valorDocumento))
```

```{r}
# Escolha três partidos e responda: Quais são os tipos de despesa mais utilizados no uso da CEAP pelos deputados desses partidos? Mesma pergunta considerando valores em R$.

dem = data %>%
  filter(sgPartido == "DEM") %>% 
  group_by(tipoDespesa) %>% 
  summarise(gastos = sum(valorDocumento))

psl = data %>%
  filter(sgPartido == "PSL") %>% 
  group_by(tipoDespesa) %>% 
  summarise(gastos = sum(valorDocumento))


avante = data %>%
  filter(sgPartido == "AVANTE") %>% 
  group_by(tipoDespesa) %>% 
  summarise(gastos = sum(valorDocumento))
```


